image: docker:latest

before_script:
  - Bem vindos a Ukanda!

services:
  - docker:dind

stages:
  - test
  - build
  - package
  - deploy

variables:
  PATH_OS:'/Teo/parte1'
  CONTAINER_NAME:itidigital
  USER_DOCKER_HUB:fantonios
  PASSWORD_DOCKER_HUB:''

test:
  stage: test
  script:
     - ./gradlew check

build:
  image: gradle:4.10
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

package:
  stage: package
  script:
    - docker build -t ${CONTAINER_NAME} .
    - docker tag ${CONTAINER_NAME} ${USER_DOCKER_HUB}/${CONTAINER_NAME}
    - docker login -u ${USER_DOCKER_HUB} -p ${PASSWORD_DOCKER_HUB}
    - docker push ${USER_DOCKER_HUB}/${CONTAINER_NAME}

deploy_staging:
  stage: deploy
  script:
    - minikube start
    - echo "Entrando dentro do path escolhido."
    - cd ${PATH_OS}
    - echo "Deployment da aplicação via Helm."
    - helm install kotlin kotlin-chart