image: gradle:4.10

stages:
  - test
  - build
  - release
  - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    
cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

build:
  stage: build
  script:
     - ./gradlew assemble

test:
  stage: test
  script:
     - ./gradlew check

release:
  stage: release
  image: docker:latest
  script:
    - cd ${APP_PATH}/release
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy_staging:
  stage: deploy
  image: fantonios/jiraya
  before_script:
    - minikube start
    - cd kotlin-chart
  script:
    - helm install kotlin-chart