# Name: Fábio Ferreira
# Data: 23/03/2020
# Version: 1.0
#
# Use the official gradle image to create a build artifact
# Image utility for create an instance with gradle

FROM gradle:latest

# Copy local code to the container image.
COPY build.grade .
COPY src ./src

# Build a release


